### ISSUE TITLE
Cannot send files over mate-bluetooth-sendto

### ISSUE THREAD

**Issue by raveit65** [mate-desktop-legacy-archive/mate-bluetooth#11]
Original bug report in fedora bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=967458

Orginal Description of problem:

Cannot send files over mate-bluetooth-sendto

Devices such as smartphones can be "linked", but cannot send files over bluetooth.

Version-Release number of selected component (if applicable):

mate-bluetooth-libs-1.6.0-1.fc19.x86_64
mate-bluetooth-1.6.0-1.fc19.x86_64

Steps to Reproduce:
1. Enable Bluetooth on your device, do visible.
2. Run mate-bluetooth-sendto and select your file want to share.

Additional info:

I added an screenshot about an error of display on "Transfer window".

**Comment by cwickert** [comment]
Did you enable receiving files in mate-file-sharing-properties?

Upstream, is there anything I can do to help you debugging?

**Comment by ghost** [comment]
I'm using arch linux kernel 3.11.6 + mate 1.6.1

Other relavent packages:
mate-bluetooth 1.6.0
mate-user-share 1.6.0
bluez4 4.101
bluez-libs 5.9
bluez-utils 5.9
obex-data-server 0.4.6
obexd-client 0.46
openobex 1.7

I can successfully pair my phone to my laptop but when I attempt to send files from my laptop to my phone I get the error message: 'Unable to find service record'

EDIT: running mate-bluetooth-sendto in a terminal allows for successful file transfer as does clicking on the 'send files to device...' option in the applet menu. The service record error message only appears if you select the bluetooth device from the devices menu and try to send files from there. Sending files from the phone to the laptop is impossible because the phone does not recognise that the laptop can recieve files I think this bug has got something to do with the applet not configuring the services of paired bluetooth devices.

**Comment by stefano-k** [comment]
In 1.8 we'll drop mate-bluetooth for blueman (https://github.com/blueman-project/blueman)

**Comment by raveit65** [comment]
Is new blueman development currently portet to bluez5?

**Comment by raveit65** [comment]
I asked because old blueman is orphaned in fedora.
https://admin.fedoraproject.org/pkgdb/acls/name/blueman?_csrf_token=c47e1dbd7568b546af5a71183d4b255cc161ac24

**Comment by stefano-k** [comment]
WIP
https://github.com/blueman-project/blueman/tree/bluez5
https://github.com/blueman-project/blueman/issues/13
